3.5.0 compatibility
pkp/bootstrap3 pull request #236
Opened 2024-12-11 21:03 UTC by kaitlinnewson

2025-01-07 19:38 UTC, asmecher requested changes
Thanks, @kaitlinnewson, lots of good tweaks here. Just a few comments to check on.

2025-01-07 19:38 UTC, asmecher commented on templates/frontend/components/registrationFormContexts.tpl
> +													{$userGroup->getLocalizedData('name')}
The `|escape` modifier should still be applied.

2025-01-07 19:38 UTC, asmecher commented on templates/frontend/components/registrationFormContexts.tpl
> +													{$userGroup->getLocalizedData('name')}
The |escape modifier should still be applied.

2025-01-07 19:38 UTC, asmecher commented on templates/frontend/objects/article_details.tpl
> +											<a href="{$author->getData('rorId')|escape}">{$rorIdIcon}</a>
This is subject to change based on @gaziyucel's active work on RORs and multiple affiliations.

2025-01-07 19:38 UTC, asmecher commented on templates/frontend/objects/article_details.tpl
> +										<a href="{$author->getData('orcid')|escape}" target="_blank">
Worth pinging @ewhanson to see how this might change with his nearly-complete ORCiD work.

2025-01-07 19:38 UTC, asmecher commented on templates/frontend/pages/contact.tpl
> +                    <div class="phone">
(Not a big deal, but there's a mix of spaces and tabs for indentation)

2025-01-08 13:22 UTC, kaitlinnewson commented on templates/frontend/objects/article_details.tpl
> +											<a href="{$author->getData('rorId')|escape}">{$rorIdIcon}</a>
Yes, I'm keeping an eye on that issue and can either wait to merge the theme updates or do another PR once that has been merged.

2025-01-09 12:08 UTC, bozana commented on templates/frontend/objects/article_details.tpl
> +										<a href="{$author->getData('orcid')|escape}" target="_blank">
I think this is already compliant with ORCID move to the core -- I am not sure, but I think the way orcid is displayed should not change any more, but maybe to double check. If it changes, it will change in the core and then also themes need to be considered (again)...

2025-01-09 13:08 UTC, kaitlinnewson commented on templates/frontend/objects/article_details.tpl
> +										<a href="{$author->getData('orcid')|escape}" target="_blank">
I confirmed with @ewhanson that there aren't further changes planned to ORCID for 3.5 that will impact the templates.

2025-02-06 22:59 UTC, merged